# GPT WAS USED TO GENERATE THIS FILE
WORD_MAPPING = {
    # Acronyms (2–3 characters)
    "ai": "AI",
    "ad": "Ad",
    "app": "App",
    "aws": "AWS",
    "bp": "BP",
    "btc": "BTC",
    "ceo": "CEO",
    "chk": "CHK",
    "crm": "CRM",
    "djia": "DJIA",
    "dia": "DIA",
    "fb": "FB",
    "ge": "GE",
    "gm": "GM",
    "gs": "GS",
    "gld": "GLD",
    "hi": "Hi",
    "htt": "HTTP",
    "iwm": "IWM",
    "ios": "iOS",
    "ip": "IP",
    "id": "ID",
    "low": "LOW",
    "mac": "Mac",
    "max": "Max",
    "na": "NA",
    "ndx": "NDX",
    "pc": "PC",
    "pot": "POT",
    "psx": "PSX",
    "qqq": "QQQ",
    "slv": "SLV",
    "spx": "SPX",
    "spy": "SPY",
    "ta": "TA",
    "try": "Try",
    "tv": "TV",
    "us": "US",
    "usd": "USD",
    "vix": "VIX",

    # Longer words (proper nouns, names, brands)
    "alexa": "Alexa",
    "america": "America",
    "amazon": "Amazon",
    "adidas": "Adidas",
    "bezos": "Bezos",
    "bidu": "BIDU",
    "bmw": "BMW",
    "cbs": "CBS",
    "china": "China",
    "colin": "Colin",
    "covid": "COVID",
    "disneyland": "Disneyland",
    "ebay": "eBay",
    "facebook": "Facebook",
    "fang": "FANG",
    "faang": "FAANG",
    "gild": "GILD",
    "goog": "GOOG",
    "google": "Google",
    "gunn": "Gunn",
    "iphone": "iPhone",
    "james": "James",
    "kaepernick": "Kaepernick",
    "kap": "Kap",
    "lenovo": "Lenovo",
    "louisville": "Louisville",
    "mark": "Mark",
    "mcdonald": "McDonald",
    "milan": "Milan",
    "nasdaq": "Nasdaq",
    "netflix": "Netflix",
    "nickelodeon": "Nickelodeon",
    "nvidia": "Nvidia",
    "nvda": "NVDA",
    "obama": "Obama",
    "reuters": "Reuters",
    "roku": "Roku",
    "samsung": "Samsung",
    "sec": "SEC",
    "shanghai": "Shanghai",
    "snap": "Snap",
    "sony": "Sony",
    "spotify": "Spotify",
    "target": "Target",
    "trump": "Trump",
    "tslaq": "TSLAQ",
    "twtr": "TWTR",
    "youtube": "YouTube",
    "zuck": "Zuck",
    "zuckerberg": "Zuckerberg"
    "iphones": "iPhones",
    "facebook": "Facebook",  # just in case still lowercase in other files
    "google": "Google",      # same reason as above
    "youtube": "YouTube",
    "twitter": "Twitter",
    "snap": "Snap",
    "wfc": "WFC",  # Wells Fargo ticker
    "eth": "ETH",  # Ethereum
    "ms": "MS",    # could be Microsoft or shorthand, but treat it uppercase
    "gop": "GOP",
    "dr": "Dr.",
    "llc": "LLC",
    "hp": "HP",
    "nbc": "NBC",
    "espn": "ESPN",
    "sap": "SAP",
    "sony": "Sony",
    "cbs": "CBS",
    "cnn": "CNN",
    "nasa": "NASA",
    "ucl": "UCL",  # UEFA Champions League
    "ip": "IP",    # in case it’s not in the original combined dict
    "reuters": "Reuters",
    "ebay": "eBay",  # casing
    "spotify": "Spotify",
    "nasdaq": "Nasdaq",
    "xbox": "Xbox",
    "mcdonald": "McDonald",
    "honda": "Honda",
    "visa": "Visa",
    "target": "Target",
    "kavanaugh": "Kavanaugh",
    "blasey": "Blasey",
    "christine": "Christine",
    "brett": "Brett",
    "sarandon": "Sarandon",
    "nooyi": "Nooyi",
    "indra": "Indra",
    "kendall": "Kendall",
    "morris": "Morris",
    "pembroke": "Pembroke",
    "tillerson": "Tillerson",
    "jamie": "Jamie",
    "dimon": "Dimon",
    "gunn": "Gunn",
    
    
    
}
